"""Routing: threshold->decision mapping and recorded-output anchoring.

The first tests are pure (no weights, no model). The fixture-anchored test
checks that, for a handful of committed prompts, the routing decision at both
documented operating points (0.161 default, 0.370 F1-optimal) matches the
decision recorded when the fixture was generated by the packaged routing path.
"""
import json
import os

import numpy as np
import pytest

from rewriter.routing_probe import (
    DEFAULT_THRESHOLD,
    DOMAINS,
    F1_OPTIMAL_THRESHOLD,
    ProbeScores,
    route_scores,
)

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")
ROUTING_CASES = os.path.join(FIXTURES, "routing_cases.json")


def test_decision_threshold_mapping():
    refuse = np.array([0.10, 0.20, 0.40])
    dom = np.tile(np.eye(8)[0], (3, 1))  # all argmax -> DOMAINS[0]
    scores = ProbeScores(refuse=refuse, domain=dom)

    at_default = route_scores(scores, threshold=DEFAULT_THRESHOLD)  # 0.161
    assert [d.decision for d in at_default] == ["REWRITE", "REFUSE", "REFUSE"]

    at_f1 = route_scores(scores, threshold=F1_OPTIMAL_THRESHOLD)  # 0.370
    assert [d.decision for d in at_f1] == ["REWRITE", "REWRITE", "REFUSE"]


def test_threshold_is_inclusive():
    scores = ProbeScores(refuse=np.array([0.161]), domain=np.eye(8)[None, 2])
    d = route_scores(scores, threshold=0.161)[0]
    assert d.decision == "REFUSE"  # >= threshold


def test_domain_argmax():
    dom = np.zeros((2, 8))
    dom[0, 5] = 0.9  # roleplay
    dom[1, 1] = 0.8  # creative_writing
    scores = ProbeScores(refuse=np.array([0.0, 0.0]), domain=dom)
    # raw path: argmax + raw max-probability confidence (calibration tested separately)
    out = route_scores(scores, domain_calibration=None)
    assert out[0].domain == DOMAINS[5]
    assert out[1].domain == DOMAINS[1]
    assert out[0].domain_confidence == pytest.approx(0.9)


def test_decision_fields():
    scores = ProbeScores(refuse=np.array([0.5]), domain=np.eye(8)[None, 3])
    d = route_scores(scores)[0]
    assert d.refuse_probability == pytest.approx(0.5)
    assert d.domain == DOMAINS[3]
    assert d.decision in ("REFUSE", "REWRITE")


@pytest.mark.skipif(not os.path.exists(ROUTING_CASES), reason="routing fixture missing")
def test_recorded_routing_cases():
    """Recorded probe scores -> decisions at 0.161 and 0.370 reproduce."""
    cases = json.load(open(ROUTING_CASES))["cases"]
    assert len(cases) >= 3
    refuse = np.array([c["refuse"] for c in cases], dtype=np.float32)
    dom = np.array([c["domain"] for c in cases], dtype=np.float32)
    scores = ProbeScores(refuse=refuse, domain=dom)

    out_default = route_scores(scores, threshold=DEFAULT_THRESHOLD)
    out_f1 = route_scores(scores, threshold=F1_OPTIMAL_THRESHOLD)
    for c, dd, df in zip(cases, out_default, out_f1):
        assert dd.domain == c["expected_domain"]
        assert dd.decision == c["decision_at_0161"]
        assert df.decision == c["decision_at_0370"]
